name: binder
on: [push]

jobs:
  Create-MyBinderOrg-Cache:
    if: "contains(github.event.head_commit.message, 'do_binder')"
    runs-on: ubuntu-latest
    steps:
    - name: cache binder build on mybinder.org
      uses: jupyterhub/repo2docker-action@master
      with:
        NO_PUSH: true
        MYBINDERORG_TAG: ${{ github.event.ref }}
        IMAGE_NAME: map573

