name: website
on:
  push:
    branches:
      - master

jobs:
  website:
    name: Build Website with rmarkdown
    if: "contains(github.event.head_commit.message, 'do_website')"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checking out repository for Github action
        uses: actions/checkout@v2
      - name: Installing additional system libraries with APT
        run: xargs -a binder/apt.txt sudo apt-get install
      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
      - name: Setting up miniconda with specified Python and R dependencies
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          environment-file: binder/environment.yml
          activate-environment: MAP573
      - name: Rendering Rmd files
        shell: bash -l {0}
        run: |
          export LANG=en_US.UTF-8
          conda run -n MAP573 Rscript binder/install.R
          conda run -n MAP573 Rscript -e 'rmarkdown::render_site(".")'
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
